### ISSUE TITLE
'ellipsis'object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by zsl946** [zhaomaoniu/nonebot-plugin-gpt-sovits#1]
配置好并启动后，发送/tts 你好，出现这个问题![20240825125737691](https://github.com/user-attachments/assets/fceacb97-918a-4fcb-aef3-400ea8e8d2c8)

**Comment by zhaomaoniu** [comment]
请更新插件到 [v0.1.1](https://github.com/zhaomaoniu/nonebot-plugin-gpt-sovits/releases/tag/v0.1.1) 后重试
